live_config_reload = true

# Colors (Tomorrow Night Bright)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#eaeaea'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#d54e53'
green   = '#b9ca4a'
yellow  = '#e6c547'
blue    = '#7aa6da'
magenta = '#c397d8'
cyan    = '#70c0ba'
white   = '#424242'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#e7c547'
blue    = '#7aa6da'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#2a2a2a'

# Colors (Tomorrow Night Bright)
# colors:
  # Default colors
# [ colors.primary ]
# background= '0x000000'
# foreground= '0xeaeaea'
  #
  # # Normal colors
# [ colors.normal ]
# black=   '0x000000'
# red=     '0xd54e53'
# green=   '0xb9ca4a'
# yellow=  '0xe6c547'
# blue=    '0x7aa6da'
# magenta= '0xc397d8'
# cyan=    '0x70c0ba'
# white=   '0x424242'
  #
  # # Bright colors
# [ colors.bright ]
# black=   '0x666666'
# red=     '0xff3334'
# green=   '0x9ec400'
# yellow=  '0xe7c547'
# blue=    '0x7aa6da'
# magenta= '0xb77ee0'
# cyan=    '0x54ced6'
# white=   '0x2a2a2a'

[colors]
draw_bold_text_with_bright_colors = false

# [colors.bright]
# black = "0x787878"
# blue = "0xb8b8b8"
# cyan = "0xa16946"
# green = "0x282828"
# magenta = "0xe8e8e8"
# red = "0xdc9656"
# # red = "0x009656"
# white = "0xf8f8f8"
# yellow = "0x383838"
# #
# [colors.cursor]
# cursor = "0xd8d8d8"
# text = "0x181818"
#
# [colors.normal]
# black = "0x000000"
# # black = "0x181818"
# blue = "0x7cafc2"
# cyan = "0x86c1b9"
# green = "0x9fbf40"
# magenta = "0xd572be"
# # magenta = "0xd572be"
# red = "0xe63932"
# # red = "0xab4642"
# white = "0xd8d8d8"
# yellow = "0xffbe3d"

# [colors.primary]
# background = "0x0f0f0f"
# foreground = "0xd8d8d8"

[font]
size = 16.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
