monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 31000
      }
    }
  }
]

device.profile.priority.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        priorities = [ "a2dp-sink", "a2dp-sink-sbc_xq", "a2dp-sink-sbc", "off" ]
      }
    }
  }
]

wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
}
