Slack = launch-or-focus slack slack
Spotify = launch-or-focus spotify spotify
# Discord = discord
Discord = launch-or-focus-webapp --profile private Discord "https://discord.com/app"
Whatsapp = launch-or-focus-webapp --profile private Discord "https://web.whatsapp.com"
Claude AI = launch-webapp "https://claude.ai/"
Google Meet = launch-or-focus-webapp --workspace meet "Google Meet" "https://meet.google.com/"
Terminal = alacritty
Tmux Sessions = SUBMENU_SES
Monitor Resolution = SUBMENU_MONRES
Apps = ~/.config/rofi/launchers/type-2/launcher.sh
