[desktop/wm/keybindings]
activate-window-menu=['<Alt>space']
begin-move=['<Alt>F7']
begin-resize=['<Alt>F8']
close=['<Alt>F4']
lower=['disabled']
minimize=['<Control><Alt>KP_0']
move-to-corner-ne=['<Control><Alt>KP_Prior']
move-to-corner-nw=['<Control><Alt>KP_Home']
move-to-corner-se=['<Control><Alt>KP_Next']
move-to-corner-sw=['<Control><Alt>KP_End']
move-to-side-e=['<Control><Alt>KP_Right']
move-to-side-n=['<Control><Alt>KP_Up']
move-to-side-s=['<Control><Alt>KP_Down']
move-to-side-w=['<Control><Alt>KP_Left']
move-to-workspace-1=['<Shift><Super>Home']
move-to-workspace-down=@as []
move-to-workspace-left=['<Primary><Shift><Super>Left']
move-to-workspace-right=['<Primary><Shift><Super>Right']
move-to-workspace-up=@as []
raise=['disabled']
show-desktop=['<Control><Super>d']
switch-applications=@as []
switch-applications-backward=@as []
switch-to-workspace-1=['<Super>Home']
switch-to-workspace-10=['disabled']
switch-to-workspace-11=['disabled']
switch-to-workspace-12=['disabled']
switch-to-workspace-5=['disabled']
switch-to-workspace-6=['disabled']
switch-to-workspace-7=['disabled']
switch-to-workspace-8=['disabled']
switch-to-workspace-9=['disabled']
switch-to-workspace-down=@as []
switch-to-workspace-left=['<Primary><Super>Left']
switch-to-workspace-right=['<Primary><Super>Right']
switch-to-workspace-up=@as []
switch-windows=['<Alt>Tab']
switch-windows-backward=['<Shift><Alt>Tab']
toggle-maximized=['<Control><Alt>KP_5']
toggle-shaded=['<Control><Alt>s']
