monitor=,preferred,auto-center-up,auto
monitor=DP-3,2560x1440@59.95Hz,auto-center-up,1
monitor=DP-5,2560x1440@74.97Hz,auto-center-up,1
monitor=eDP-1,preferred,auto-center-down,1
monitor=HDMI-A-1,2560x1440@59.95Hz,auto-center-up,1
monitor=DP-1,2560x1440@59.95Hz,auto-center-up,1
monitor=DVI-I-1,2560x1440@59.95Hz,auto-center-up,1
